name: DL K8s Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: '327.0.0'  
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Set the GCP service account key as a secret in your repository

      - name: Configure Docker for GCR authentication
        run: |
          gcloud auth configure-docker "${{ env.REGISTRY_LOCATION }}"

      - name: Build and push Docker image to Google Container Registry (GCR)
        env:
          REGISTRY_LOCATION: gcr.io/${{ env.PROJECT_ID }}
          IMAGE_TAG: v1
        run: |
          gcloud builds submit --tag="${{ env.REGISTRY_LOCATION }}/myapp:${{ env.IMAGE_TAG }}" .

      - name: Deploy to Kubernetes
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          CLUSTER_NAME: mykube
          LOCATION: europe-west9
        run: |
          gcloud container clusters get-credentials "${{ env.CLUSTER_NAME }}" --region="${{ env.LOCATION }}"
          kubectl apply -f K8s/
